main.py
from flask import Flask
from routes.home import home_route
from routes.cliente import cliente_route


# inicialização
app = Flask(__name__)

app.register_blueprint(home_route)
app.register_blueprint(cliente_route, url_prefix='/clientes')

# execucao
app.run(debug=True)

routes/cliente.py
from flask import Blueprint, render_template, request
from database.cliente import CLIENTES

cliente_route = Blueprint('cliente', __name__)

@cliente_route.route('/')
def lista_cliente():
    """ listar os clientes """
    return render_template('lista_clientes.html', clientes=CLIENTES)



@cliente_route.route('/', methods=['POST'])
def inserir_cliente():
    """ inserir os dados do cliente """
    
    data = request.json

    novo_usuario = {
        "id": len(CLIENTES) + 1,
        "nome": data['nome'],
        "email": data['email'],
    }

    CLIENTES.append(novo_usuario)
    return render_template('item_cliente.html', cliente=novo_usuario)




@cliente_route.route('/new')
def form_cliente():
    """ formulario para cadastrar um cliente"""
    return render_template('form_cliente.html')



@cliente_route.route('/<int:cliente_id>')
def detalhe_cliente(cliente_id):
    """ formulario para cadastrar um cliente"""

    # Filter com lambda, retorna o cliente que possui o mesmo id do DB CLIENTES,
    # usando Lambda para não precisar usar o "for" como nas outras rotas
    cliente = list(filter(lambda c: c['id'] == cliente_id, CLIENTES))[0] # refaz uma lista com 1 item (que seria o usuario com o ID)
    return render_template('detalhe_cliente.html', cliente=cliente)



@cliente_route.route('/<int:cliente_id>/edit')
def form_edit_cliente(cliente_id):
    """ formulario para editar um cliente"""

    # obtem usuario pelo id
    cliente = None
    for c in CLIENTES:
        if c['id'] == cliente_id:
            cliente = c

    return render_template('form_cliente.html', cliente=cliente)



@cliente_route.route('/<int:cliente_id>/update', methods=['PUT'])
def atualizar_cliente(cliente_id):
    """ atualizar informações do cliente """
    cliente_editado = None
    # obter dados do formulario de edição
    data = request.json

    # obter usuario pelo id
    for c in CLIENTES:
        if c['id'] == cliente_id:
            c['nome'] = data['nome']
            c['email'] = data['email']

            cliente_editado = c

    # editar usuario
    return render_template('item_cliente.html', cliente=cliente_editado)



@cliente_route.route('/<int:cliente_id>/delete', methods=['DELETE'])
def deletar_cliente(cliente_id):
    global CLIENTES
    # o primeiro 'c' é o que vamos colocar na nova lista
    # ou seja, para cada C em CLIENTES, vai colocar na nova lista apenas o C que tiver ID diferente do ID do Cliente
    # cria uma nova lista sem o cliente que desejamos remover
    CLIENTES = [ c for c in CLIENTES if c['id'] != cliente_id]
    return {'deleted': 'ok'}

routes/home.py
from flask import Blueprint, render_template

home_route = Blueprint('home', __name__)

@home_route.route('/')
def home():
    return render_template('index.html')

templates/detalhe_cliente.html
<ul>
    <li>ID: {{cliente.id}}</li>
    <li>NOME: {{cliente.nome}}</li>
    <li>EMAIL: {{cliente.email}}</li>
</ul>

templates/form_cliente.html
<form class="c-form"
  {% if cliente %}
    action="{{ url_for('cliente.atualizar_cliente', cliente_id=cliente.id) }}" 
  {% else %}
    action="{{ url_for('cliente.inserir_cliente') }}" 
  {% endif %}

  method="{% if cliente %}PUT{% else %}POST{% endif %}"
  
  {% if cliente %}
    c-swap="#cliente-{{ cliente.id }}"
  {% else %}
    c-append="#lista-clientes"

  {% endif %}
  >

  <div class="mb-3">
    <label class="form-label">Nome</label>
    <input type="text" class="form-control" name="nome" {% if cliente %}value="{{cliente.nome}}"{% endif %}>
  </div>

  <div class="mb-3">
    <label class="form-label">Email</label>
    <input type="text" class="form-control" name="email" {% if cliente %}value="{{cliente.email}}"{% endif %}>
  </div>

  <button type="submit" class="btn btn-primary">
    {% if cliente %}Salvar{% else %}Criar{% endif %}
  </button>

</form>

templates/index.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <!-- Meta tags Obrigatórias -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/app.css') }}">
    <title>Olá, mundo!</title>
  </head>
  <body>
    
    <div class="container">
      <h1 class="text-center">Gestão de Clientes</h1>

      <!-- Formulário add cliente -->
      <div id="form-cliente" c-container="{{ url_for('cliente.form_cliente') }}"></div>

      <hr>

      <h2>Lista de Clientes</h2>
      <!-- Lista de clientes -->
      <div c-container="{{ url_for('cliente.lista_cliente') }}"></div>      
    </div>


    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body" id="exibir-cliente"></div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
          </div>
        </div>
      </div>
    </div>
    

    <!-- JavaScript (Opcional) -->
    <!-- jQuery primeiro, depois Popper.js, depois Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>


    <script src="{{ url_for('static', filename='js/cru.js') }}"></script>




  </body>
</html>

templates/item_cliente.html
<tr id="cliente-{{ cliente.id }}">
  <th scope="row">{{ cliente.id }}</th>
  <td>{{ cliente.nome }}</td>
  <td>{{ cliente.email }}</td>
  <td>

    <button class="btn btn-secondary"
      c-get="{{ url_for('cliente.detalhe_cliente', cliente_id=cliente.id) }}" 
      c-target="#exibir-cliente" 
      data-bs-toggle="modal" data-bs-target="#exampleModal">
        Ver
    </button>

    <button class="btn btn-primary"
      c-get="{{ url_for('cliente.form_edit_cliente', cliente_id=cliente.id) }}" 
      c-target="#form-cliente">
        Editar
    </button>
    
    <button class="btn btn-danger" c-delete="{{ url_for('cliente.deletar_cliente', cliente_id=cliente.id) }}"
      c-remove-closest="tr">Deletar</button>
  </td>
</tr>

templates/lista_clientes.html
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nome</th>
      <th scope="col">Email</th>
      <th scope="col">Ações</th>
    </tr>
  </thead>
  <tbody id="lista-clientes">
    
    {% for cliente in clientes %}
      {% include 'item_cliente.html' %}
    {% endfor %}

  </tbody>
</table>